"""add_truck_location_tracking_fields

Revision ID: 82f7a1c2db9b
Revises: 439315a1cb2f
Create Date: 2026-09-27 12:00:51.341462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f7a1c2db9b'
down_revision: Union[str, Sequence[str], None] = '439315a1cb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('speed_kmph', sa.Float(), nullable=True))
    op.add_column('trucks', sa.Column('heading', sa.Integer(), nullable=True))
    op.add_column('trucks', sa.Column('location_status', sa.String(), nullable=True))
    op.add_column('trucks', sa.Column('last_location_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'last_location_update')
    op.drop_column('trucks', 'location_status')
    op.drop_column('trucks', 'heading')
    op.drop_column('trucks', 'speed_kmph')
    # ### end Alembic commands ###
